### ISSUE TITLE
Mexico R Algorithm Registration

### ISSUE THREAD

**Issue by wildintellect** [CEOSBiomassHarmonization/NASA_CMS#1]
Todo list of things to prepare NASA_CMS_2023/Mexico/DPS_algorithm for registration. (Ported from [Gitlab](https://repo.maap-project.org/lduncanson/biomass_harmonization/-/issues/1))

## build_command.sh
- [x] Remove `conda install` commands from build
- [x] Change env name to `r` , drop libmamba (redundant in r:v3.1.5)
- [x] Add a call to an Rscript just for installing INLA, split this from the main R file (should this use conda run?)
```
options(repos=c(CRAN="https://cloud.r-project.org/"))
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
```

## run_GMBpredictions_MEX.yaml
- [x] update docker image to `r:v3.1.5`
- [x] Change repo url to new github repo `https://github.com/CEOSBiomassHarmonization/NASA_CMS.git`
## run_GMBpredictions_MEX.sh
- [x] should this wrap Rscript in conda run?

## GMB_Mexico.R
- [x] remove the INLA install

**Comment by wildintellect** [comment]
The INLA installation doesn't work if you try `dep=TRUE`. We need to figure out what Dependencies might be missing and add them via `conda` installs if necessary. @nehahunka do you know what Suggested packages are actually required for your code? https://github.com/hrue/r-inla/blob/devel/rinla/DESCRIPTION

**Comment by nehahunka** [comment]
Yes, I struggled with dependencies. The ones I installed separately and needed were "fmesher" and "MatrixModels"...eventually everything worked when I did the following: 

In R: 
```

# install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
# install.packages("fmesher", dependencies = TRUE)
# install.packages("MatrixModels", type = "source")
# install.packages("exactextractr")
# install.packages("sn" ,dependencies = TRUE)
# packages <- c("terra","dplyr","spdep", "exactextractr", "sf","ggplot2","viridis","sn","fmesher","exactextractr","fields")
# package.check <- lapply(packages, FUN = function(x) {
#     if (!require(x, character.only = TRUE)) {
#         install.packages(x, dependencies = TRUE)
#         library(x, character.only = TRUE, quietly=TRUE)
#     }
# })
# Sys.setenv("AWS_DEFAULT_REGION" = 'us-west-2')

# ##### CONDA-FORGE YOUR WAY THROUGH PACKAGES THAT DID NOT INSTALL ##########

# conda install conda-forge::r-fmesher
# conda install conda-forge::r-exactextractr
# conda install conda-forge::r-sn
# conda install conda-forge::r-inlabru
# conda install conda-forge::r-fields
```

**Comment by wildintellect** [comment]
Algorithm registration is successful, R install is working based on initial tests. Outputs still need to be verified.

**Comment by wildintellect** [comment]
For reference in MAAP the correct approach is the `conda` method.
1. Create the environment yaml file for the R packages that are available (all but INLA)https://github.com/CEOSBiomassHarmonization/NASA_CMS/blob/482c69201f9d866aca376909b8208609da5234e2/NASA_CMS_2023/Mexico/DPS_algorithm/env_main_ADE.yaml#L1-L16
2. Install to the conda env https://github.com/CEOSBiomassHarmonization/NASA_CMS/blob/482c69201f9d866aca376909b8208609da5234e2/NASA_CMS_2023/Mexico/DPS_algorithm/build_command_main_ADE.sh#L5
4. Install INLA using an R command (in dps do this during the build, not the job) https://github.com/CEOSBiomassHarmonization/NASA_CMS/blob/482c69201f9d866aca376909b8208609da5234e2/NASA_CMS_2023/Mexico/DPS_algorithm/build_command_main_ADE.sh#L8
